# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da471884b064cf33e5270d218e4f006f2335ce71117e1c567a40ab5f6eda02894846542af232313b65fa729bf1a7615be6935f62bfda0bb7751b579131f4ed5e

test:
  secret_key_base: 2371cac6965cad4abcb3893bc88dba6b741ee775113dcfdb35b14394123a67689fcd427e0df4c9701ea9d8c82173c00ef15204f291820f642a751dccc16e3ddf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
